#=========================== DB CONFIG ===========================================
spring.datasource.url= jdbc:mysql://localhost:3306/dop?autoReconnected=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.tomcat.test-while-idle=true

#========================= File Locations ==========================
directory.file.location=C:/Users/eddyb/Desktop/files/waiting/TechCrunchcontinentalUSA.csv
directory.file.outbound.target=C://Users//eddyb//Desktop//files//waiting//target.csv

