batch.dataSource.url=jdbc:mysql://localhost:3306/customer?autoReconnected=true&useSSL=false
batch.dataSource.driverClassName=com.mysql.jdbc.Driver
batch.dataSource.password=root
batch.dataSource.username=root
batch.dataSource.max-active=100
batch.dataSource.max-idle=8
batch.dataSource.min-idle=8
batch.dataSource.initial-size=10

#batch.dataSource2.url=jdbc:mysql://localhost:3306/customer?autoReconnected=true&useSSL=false
#batch.dataSource2.driverClassName=com.mysql.jdbc.Driver
#batch.dataSource2.password=root
#batch.dataSource2.username=root



