batch.dataSource.url=jdbc:mysql://localhost:3306/customer?autoReconnected=true&useSSL=false
batch.dataSource.driverClassName=com.mysql.jdbc.Driver
batch.dataSource.password=root
batch.dataSource.username=root

