batch.dataSource.url=jdbc:mysql://localhost:3306/customer?autoReconnected=true&useSSL=false
batch.dataSource.driverClassName=com.mysql.jdbc.Driver
batch.dataSource.password=root
batch.dataSource.username=root
batch.dataSource.max-active=100
batch.dataSource.max-idle=8
batch.dataSource.min-idle=8
batch.dataSource.initial-size=10

#================================ File Location ===============================
batch.resources.waiting=C:\\spring.batch.resources\\waiting\\customers.csv
batch.resources.processing=C:\\spring.batch.resources\\processing\\customers.csv
batch.resources.error=C:\\spring.batch.resources\\error\\
batch.resources.processed=C:\\spring.batch.resources\\processed\\


#================================ Error Skip and Policy ===========================
batch.skipPolicy.skippedLines=C:\\spring.batch.resources\\skippedLines\\skippedLines_FILE.csv
batch.skipPolicy.skipErrorLimit=5




